// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCylciYZuzg70M3I22HPd01z83NFr67_eE',
    appId: '1:744525814170:web:0e71b862744460b6be4223',
    messagingSenderId: '744525814170',
    projectId: 'project-c5dd2',
    authDomain: 'project-c5dd2.firebaseapp.com',
    storageBucket: 'project-c5dd2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAstDHHdxGBvHrlnQd7KPIBLbMqTTKr0Q',
    appId: '1:744525814170:android:d7e211818fefbd67be4223',
    messagingSenderId: '744525814170',
    projectId: 'project-c5dd2',
    storageBucket: 'project-c5dd2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrXB4Hg3rYIKhYMOEatUqz-xD0qwmJRZ4',
    appId: '1:744525814170:ios:8460a52e39543285be4223',
    messagingSenderId: '744525814170',
    projectId: 'project-c5dd2',
    storageBucket: 'project-c5dd2.firebasestorage.app',
    iosBundleId: 'com.example.ludo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrXB4Hg3rYIKhYMOEatUqz-xD0qwmJRZ4',
    appId: '1:744525814170:ios:8460a52e39543285be4223',
    messagingSenderId: '744525814170',
    projectId: 'project-c5dd2',
    storageBucket: 'project-c5dd2.firebasestorage.app',
    iosBundleId: 'com.example.ludo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCylciYZuzg70M3I22HPd01z83NFr67_eE',
    appId: '1:744525814170:web:3ea329e362ee69efbe4223',
    messagingSenderId: '744525814170',
    projectId: 'project-c5dd2',
    authDomain: 'project-c5dd2.firebaseapp.com',
    storageBucket: 'project-c5dd2.firebasestorage.app',
  );
}
